version: '3'
services:
  composer:
    container_name: composer_installation
    image: composer:2.2.7
    environment:
      - COMPOSER_CACHE_DIR=/var/www/
    volumes:
      - ./:/app
    command: sh -c "composer install --ignore-platform-reqs"
  php:
    image: php:8.1.1-fpm
    volumes:
      - ./:/app
    working_dir: /app 
  web:
    image: nginx:alpine
    ports:
      - '8000:80'
    volumes:
      - ./docker/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/app  
    depends_on:
      - php
#  phpunit:
#      image: php:8.1.1-cli
#      depends_on:
#        - composer
#      links:
#        - composer 
#      volumes:
#        - ./:/app
#      working_dir: /app
#      entrypoint: vendor/phpunit/phpunit/phpunit  